### ISSUE TITLE
Exporting Database from firestore to PDF or External documents

### ISSUE THREAD

**Issue by sboutros22** [sboutros22/CowHandlerV2#17]
The rancher want the ability to transfer the dataset into pdf or other document form either for security or to have paper copies. Regardless, it should be done using the app and not having to download the dataset from the Firebase website. This needs to be looked into more and be confirmed if it is possible using Android Studio.

**Comment by jgurary** [comment]
You can dump the dataset as JSON and leave this for the future. Leave it alone until the rest of the app is functional.

**Comment by joelyjimbob** [comment]
PDF creation is capable, though the layout of pdfs is not great. I will create a separate issue for that.
