### ISSUE TITLE
Getting it all to start working

### ISSUE THREAD

**Issue by sboutros22** [sboutros22/CowHandlerV2#2]
We need to see how we can create branches off of github and see if they affect our own code in android studio

**Comment by sboutros22** [comment]
We have to create a branch from android studio as far as I can tell making one in github does nothing. So how do we get it so all of you can add a branch from your andriod studios and link them to this github so we can start putting it together

**Comment by jgurary** [comment]
Creating branches isn't really an Issue, just a general activity. You should have more concrete tasks assigned for individual team mates to tackle.

**Comment by joelyjimbob** [comment]
I'd say it's started working to some extent, but this is a vague issue, so I'm going to close it to maintain real focus on issues.
