### ISSUE TITLE
Need to start combining our own individual works together

### ISSUE THREAD

**Issue by sboutros22** [sboutros22/CowHandlerV2#3]
Once we figure out how this github thing works with android studio we need to combine our own code together. For now its best that we work on our own branches. And not to mess with the master, because what ever happens in master happens to my android studio.

**Comment by jgurary** [comment]
This isn't really a specific Issue, just a general team coordination thing. A more specific issue might be for everyone to commit a sample change to a branch and pull it into main.

**Comment by joelyjimbob** [comment]
We have all committed to master at one point or another, so I am closing this.
