### ISSUE TITLE
Incorporate Edit/Delete cow functions into ViewCow page.

### ISSUE THREAD

**Issue by joelyjimbob** [sboutros22/CowHandlerV2#35]

**Comment by sboutros22** [comment]
I can add buttons in the ViewCow page that would take the user to those respected pages. I could also later change the delete into a confirmation delete button to avoid having to leave the ViewCow page. I think the edit cow one would still need to take you  to the other page though.

**Comment by sboutros22** [comment]
The buttons have been created, the delete cow button is functional. The edit cow button still needs to be hooked up properly but I recommend fixing EditEntry before that though. Also still need the alert feature for the delete button.
