### ISSUE TITLE
Functioning landing page

### ISSUE THREAD

**Issue by jgurary** [sboutros22/CowHandlerV2#8]
Create a functioning landing page, the page that application starts at. 

Links to the "Add a Cow" page (and others).

Attach mockup and/or page description to this issue.

**Comment by loveslota** [comment]
[RanchHandLandingPg.pdf](https://github.com/sboutros22/CowHandlerV2/files/9675473/RanchHandLandingPg.pdf)

The landing page that the user should see after signing in will be the home screen. The home landing page will have a component that displays the user's credentials and 4 button components. The button components should take the user to the appropriate pages.
